In [31]:
import numpy as np

# Set the random seed for reproducibility
np.random.seed(42)

# Example nodes and positive edges
nodes = [0, 1, 2, 3]
positive_edges_set = {(0, 1), (1, 2)}

num_negatives = 4
num_nodes = len(nodes)
negative_edges = []

while len(negative_edges) < num_negatives:
    edges = np.random.randint(0, num_nodes, size=(2, num_negatives - len(negative_edges)))
    for edge in edges.T:
        if edge[0] != edge[1] and (edge[0], edge[1]) not in positive_edges_set and (edge[1], edge[0]) not in positive_edges_set:
            negative_edges.append(edge)

negative_edges = np.array(negative_edges)

print("Negative edges:\n", negative_edges)


Negative edges:
 [[2 0]
 [0 3]
 [3 2]
 [1 3]]


In [7]:
import numpy as np

num_nodes = 5
num_negatives = 10
negative_edges = [(0, 1), (2, 3), (1, 4), (3, 0)]  # Example already existing negative edges

edges = np.random.randint(0, num_nodes, size=(2, num_negatives - len(negative_edges)))
print(edges)


[[0 3 3 1 4 0]
 [1 0 1 3 1 2]]
